item {
	id: 1
	name: 'lemon'
}
item {
	id: 2
	name: 'glasses'
}
item {
	id: 3
	name: 'coke'
}
item {
	id: 4
	name: 'cider'
}
item{
	id: 5
	name: 'apple'
}
item{
	id: 6
	name: 'banana'
}
item{
	id: 8
	name: 'watch'
}
item{
	id: 9
	name: 'ebi'
}
item{
	id: 10
	name: 'smartphone'
}
item{
	id: 11
	name: 'cup'
}
